### ISSUE TITLE
Different vertical spacing for inline vs display

### ISSUE THREAD

**Issue by JesusTorrado** [karthink/org-preview#3]
Hi @karthink 

I know this code is not developed in this repo any more, but I didn't know where to put this.

The current approach to previews looks quite vertically crammed, more than the equivalent latex-rendered full document, because the spacing around *display* math (as opposed to *inline* math) is minimal. This could theoretically be solved in the current approach (e.g. with an `imagemagick` macro), but any solution would apply to both display and inline, which defeats the purpose.

So, if you could make it so that the vertical spacing can be directly managed in display math, that would be amazing! Even more so if one can pass general options to the rendering pipeline for display and inline separately.

Amazin work, BTW! I cannot wait to have it in the stable org package!

**Comment by ltmsyvag** [comment]
Same problem here. Hope it gets solved. This new preview is going to be revolutionary. Can't wait to use the perfected version

**Comment by karthink** [comment]
@JesusTorrado @ltmsyvag I think I misunderstood your messages. Are you talking about the work-in-progress library `org-latex-preview` that is going to be part of Org, or about the code in this repo?

**Comment by JesusTorrado** [comment]
It is a feature request for the work-in-progress library that is going to be part of `org`.

For me, the ideal outcome would be that there is a option controlling the amount of vertical padding (maybe also left padding) for display math (but not inline math).

Again, thanks for the great work!

**Comment by karthink** [comment]
> It is a feature request for the work-in-progress library that is going to be part of org.

I assume you're already using this then.

You can control the page width of the images using the variable `org-latex-preview-width`.

You can control the padding above/below the images by setting `\abovedisplayskip` and `\belowdisplayskip` as you would in latex, in the variable `org-latex-preview-preamble`. (This is untested.)

For future reference, this feature is being discussed, in decreasing order of platform freedom, 
- on the Org mailing list (primary, preferred means),
- the [org-mode Matrix server](https://matrix.to/#/#org-mode:matrix.org).
- and the Doom Emacs Discord server.

I also keep an eye on the [Emacs subreddit](https://old.reddit.com/r/emacs).

**Comment by JesusTorrado** [comment]
That's great! Thank you!

**Comment by JesusTorrado** [comment]
Sorry for necromancing a closed issue, but I think it's good to leave this here for reference:

> You can control the padding above/below the images by setting \abovedisplayskip and \belowdisplayskip as you would in latex, in the variable org-latex-preview-preamble. (This is untested.)

After some experiments I can confirm that this approach does **not** work, since the padding controlled by these settings is added only when there is text around the equation. Thus the dvi/pdf file passed to e.g. `dvisvgm` does not contain that padding.

As stated above, this could still be solved by adding some options to the converter, but that would need separate pipelines/options for rendering display vs inline math, which seems not to be present at the moment.

Alternatively, it could be based on fiddling with bounding boxes of display environments using some package à la [empheq](https://ctan.org/pkg/empheq). This would be even better, since the alignment and padding would be more content-aware. I am doing some experiments at the moment.

Again, this is not at all a complaint at all, @karthink. I am extremely grateful for your work on this!
